INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 1/2', '15', '30', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 2/2', '15', '30', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('ISPIT BEZ MINIMUMA', '0', '40', '30');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('ISPIT BEZ USLOVA 1', '0', '50', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('ISPIT BEZ USLOVA 2', '0', '40', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('ISPIT SA MINIMUMOM', '10', '40', '30');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 1/3', '0', '20', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 2/3', '0', '20', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 3/3', '0', '20', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 1/4', '0', '15', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 2/4', '0', '15', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 3/4', '0', '15', '0');
INSERT INTO `ssluzba`.`tip_polaganja` (`naziv`, `minimalno_za_prolaz`, `ukupno`, `minimalno_za_uslov`) VALUES ('KOLOKVIJUM 4/4', '0', '15', '0');
